name: Rust Build and Release
on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0
env:
  CARGO_TERM_COLOR: always
  RELEASE_BIN: xloge
permissions:
  contents: write
jobs:
  build:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: macos-13
            artifact_name: xloge
            asset_name: xloge-macos-x64
          - os: macos-latest
            artifact_name: xloge
            asset_name: xloge-macos-arm64
            rust_target: aarch64-apple-darwin
    
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: ${{ matrix.rust_target }}
    
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features ${{ matrix.rust_target && format('--target {0}', matrix.rust_target) }}
    
    - name: Prepare artifact path
      id: artifact-path
      run: |
        if [ "${{ matrix.rust_target }}" != "" ]; then
          echo "path=target/${{ matrix.rust_target }}/release/${{ matrix.artifact_name }}" >> $GITHUB_OUTPUT
        else
          echo "path=target/release/${{ matrix.artifact_name }}" >> $GITHUB_OUTPUT
        fi
        
    - name: Rename binary
      run: |
        cp ${{ steps.artifact-path.outputs.path }} ${{ matrix.asset_name }}
        chmod +x ${{ matrix.asset_name }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.asset_name }}
        retention-days: 5

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./
      
      - name: List files
        run: |
          find . -type f -executable
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ./xloge-macos-x64/xloge-macos-x64
            ./xloge-macos-arm64/xloge-macos-arm64